[tool.black]
line-length = 120
target-version = ['py33']

# regex
exclude = '''
/(
  \.git |
  language-server |
  plugin/libs |
  stubs
)/
'''

[tool.pyright]
include = ["./"]
exclude = [
  "**/__pycache__/",
  "**/node_modules/",
  # git-related
  "**/.git/",
  "**/br-*/",
  "**/branch-*/",
]
ignore = []
stubPath = "typings"
pythonVersion = "3.8"
venvPath = "."
venv = ".venv"
